import { LiveTester } from "@/app/components/live-tester";

export default function Home() {
  const curlExample = `curl -X POST https://your-api.vercel.app/api/v1/personalize \\
  -H "Content-Type: application/json" \\
  -H "x-api-key: YOUR_API_KEY" \\
  -d '{"company": "Notion", "role": "Head of Sales"}'`;

  const responseExample = `{
  "prospect": {
    "name": "Unknown Prospect",
    "role": "Head of Sales",
    "company": "Notion"
  },
  "lines": [
    {
      "tone": "curious",
      "text": "Saw your recent momentum and was curious what your biggest sales priority is right now."
    },
    {
      "tone": "direct",
      "text": "Noticed your team is scaling, so I wanted to share a direct thought based on your current focus."
    },
    {
      "tone": "compliment",
      "text": "Your positioning and execution stand out, especially for the stage your team is in."
    }
  ],
  "usage": {
    "requests_used": 42,
    "requests_limit": 1000
  }
}`;

  return (
    <div className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-5 py-8 sm:px-8 lg:gap-8 lg:py-14">
      <header className="fade-in-up card p-6 sm:p-8">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border)] pb-4">
          <p className="text-sm font-medium tracking-wide text-[var(--brand-strong)]">Cold Email Personalizer API</p>
          <p className="text-sm text-[var(--muted)]">v1 - REST + JSON</p>
        </div>
        <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_1fr] lg:items-end">
          <div>
            <h1 className="max-w-2xl text-3xl font-semibold leading-tight sm:text-4xl">
              Generate personalized cold email opening lines from LinkedIn or company context.
            </h1>
            <p className="mt-4 max-w-2xl text-base leading-7 text-[var(--muted)] sm:text-[17px]">
              Send a LinkedIn profile URL or company name and receive 3 human-sounding openers in curious, direct, and compliment tones.
            </p>
          </div>
          <div className="grid gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface-alt)] p-4 text-sm text-[var(--muted)]">
            <p>p95 response target: &lt; 3000ms</p>
            <p>Free tier: 1000 requests/month</p>
            <p>AI provider: Gemini 3.1 Flash Lite</p>
          </div>
        </div>
      </header>

      <div className="fade-in-up [animation-delay:70ms]">
        <LiveTester />
      </div>

      <main className="fade-in-up space-y-5 [animation-delay:90ms]">
        <article className="card p-5 sm:p-6">
          <div className="flex items-center justify-between gap-3">
            <h2 className="text-lg font-semibold">Quick start</h2>
            <span className="text-xs uppercase tracking-wide text-[var(--muted)]">POST /api/v1/personalize</span>
          </div>
          <p className="mt-2 text-sm leading-7 text-[var(--muted)]">Use API key auth and send either a LinkedIn URL or company + role payload.</p>
          <pre className="mt-4 overflow-x-auto rounded-lg border border-[var(--border)] bg-[#f8faf8] p-4 text-sm leading-6 text-[#22312c]">
            <code>{curlExample}</code>
          </pre>
        </article>

        <article className="card p-5 sm:p-6">
          <h2 className="text-lg font-semibold">Response shape</h2>
          <p className="mt-2 text-sm leading-7 text-[var(--muted)]">
            Production responses include structured prospect data, generated lines, and usage tracking.
          </p>
          <pre className="mt-4 max-h-[320px] overflow-auto rounded-lg border border-[var(--border)] bg-[#faf8f4] p-4 text-sm leading-6 text-[#2b2318]">
            <code>{responseExample}</code>
          </pre>
        </article>

        <section className="card p-5 sm:p-6">
          <h2 className="text-lg font-semibold">Operational notes</h2>
          <div className="mt-4 grid gap-3 text-sm sm:grid-cols-3">
            <div className="rounded-lg border border-[var(--border)] bg-[var(--surface-alt)] p-3">
              <p className="font-medium">Authentication</p>
              <p className="mt-1 leading-6 text-[var(--muted)]">x-api-key is required on all /api/v1 requests.</p>
            </div>
            <div className="rounded-lg border border-[var(--border)] bg-[var(--surface-alt)] p-3">
              <p className="font-medium">Rate limits</p>
              <p className="mt-1 leading-6 text-[var(--muted)]">Per-key monthly limits are enforced server-side.</p>
            </div>
            <div className="rounded-lg border border-[var(--border)] bg-[var(--surface-alt)] p-3">
              <p className="font-medium">Generation</p>
              <p className="mt-1 leading-6 text-[var(--muted)]">Lines are generated by Gemini using public context signals.</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
